dist: trusty
sudo: false
language: ruby
bundler_args: "--without assets:development:production"
addons:
  postgresql: '9.6'
cache: bundler
before_script: bundle exec rake db:create db:schema:load
script:
- bundle exec rake
- bundle exec rubocop
deploy:
  provider: heroku
  api_key:
    secure: FJzBPmNVyyoCjx5QmBt49ggv5PUhSB911Wub67oBVOSuzZZtmmNqGWYcEEfZBxUbahcFXPuvnIJHSfovqGf3vfotgKeL/QpOzysBaTRBtB5G8uReq7R9o7g+Q1Rd+5Xff4XMMpLM3dFYClLa0izTv0XkfMcU0fcLQFmH4E2MHH/dXhsWCBYX6JVv0zew/cfsbkZZ72jB5dByX7RDderrI+ypreQiPtfS8uAxh4VdqV4Pzz+MG6OjZZGPQ1q8JgHgX24G+pvpWg8gGEA/nH1j9nVefKYdfyduCmyk0gnxMeMcw1pq+qxbcN0Za4CBSp0IWo/JUEbi3n9Kn1So9DqciVzJ4he4f0bwX6qsb92Wb9D5/PuCzanx2E1XiFh0ocrWey2H1GO8KCbAYHSvX60Z7I7um8280+Tdo5jUjsdC95hu9IyFENPpR0z3rObNRF1fJROOilwQbJIpvyjzw8dO3fzLFjaPNpN8azG97HarT4XY3BZRyhgZZHWw/CGnNuBy+YPlxexwSesEY8ep5isbXrX04oGYDab90Dtpq2NFN1E/qdS7m0VKfXFAfDHOwt8EMUjecNKOe1gFYdFMuIP5rmzzNk/Z28IMnAFjESAc40QcPqZ+Kkp2suCzCIyN3wAJVGnexMZBqAMcT9tDkFCvm3DiOaO+hiO+WJyJ2Uaa7OY=
  app: adoptadrainsf-staging
  on:
    repo: sfbrigade/adopt-a-drain
    branch: master
